### ISSUE TITLE
Installing Pytorch-1.7 on PYNQ - ZCU104

### ISSUE THREAD

**Issue by mryan-raihaan** [manoharvhr/PYNQ-Torch#4]
Hi, I would like to use pytorch on pynq (ZCU 104 board). However, after follows your instructions on this page, I am stuck when build the pytorch. 
Here, is the error message. I have tested both on the desktop and on the board. Both shows the same error. Could you please help me with this. Many thanks

sudo python3 setup.py build

Building wheel torch-1.7.0a0
-- Building version 1.7.0a0
cmake --build . --target install --config Release -- -j 8
make: *** No rule to make target 'install'.  Stop.
Traceback (most recent call last):
  File "setup.py", line 717, in <module>
    build_deps()
  File "setup.py", line 313, in build_deps
    cmake=cmake)
  File "/home/mryan/pytorch_1.7/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/mryan/pytorch_1.7/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/mryan/pytorch_1.7/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 2.

**Comment by mryan-raihaan** [comment]
Sorry, It is already solved. My bad. As I am trying to build PyTorch v1.7, so I should first install all the requirements/dependencies, stated on the PyTorch github page
